# File: .github/workflows/docker-build-push.yml
name: Build and Push Docker Image

on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./main.yml
        with:
          docker-repo-name: 'mukesh18s/prod'
