# File: .github/workflows/docker.yml (in your main repository)
name: Trigger Shared Workflow

on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  trigger_shared_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Shared Workflow in shared-workflow2
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: mukeshsirvi18/shared-workflow2
          event-type: build-docker-image
          client-payload: '{"docker-repo-name": "mukesh18s/prod"}'
