# File: .github/workflows/docker-build-push.yml
name: Build and Push Docker Image

on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  Build:
    uses: /shared-workflow2/.github/workflows/main.yml@main
    with:
        docker-repo-name: 'mukesh18s/prod'
